### ISSUE TITLE
Can't compile in Windows 10

### ISSUE THREAD

**Issue by Ivan-Adriazola** [LLNL/psuade#3]
I'm kind of new in this git thing so sorry if this isn't the place to post this.

I've actually tried lots of stuff, I've tried with three MS Windows 10 versions, one of the earliest w10 versions rufus has to offer, one in the middle and one that was the one i used and was one of the latest.

**In cmake gui**

After reading the _"cmakelists.txt"_, I noticed that it could also work if I had preinstalled lapack so I installed the latest version, _"lapack 3.9.0"_ with the #370 fix.

but that didn't help. it still failed to find "sgemm" and _"pthread"_, I read somewhere on the internet that it may be because the gfortran version the latest mingw installs may be incompatible with some programs so I downloaded new compilers and that also didnt work (it worked only for pthread)

I resorted to get an old installations of _"Mingw32"_ (the 2012 version), and that actually helped, I was finally able to configure and generate in _"Cmake"_

**In CMD with mingwmake**

Sadly it failed to recognize _"lbfgsb.h"_ in _"GP3.cpp"_ at 73%, I know this was the cause because the command windows showed a lot of messages in the format of 

> integers was not declared in this scope
> IS_FG was not declared in this scope

I tryed to remove the conditional from _"GP3.cpp"_ that made _"lbfgsb.h"_ not be recognized and let it always be included 

then it got up to 83% but then it failed to recognize some .max and .min commands, I dont actually remember how i worked around this, but it was a including some .h file in the file in question.

After doing that it started showing

> undefined reference to setulb 
> undefined reference to newuoa_ 

I tried including _"lbfgsb.h"_ in the files that used setulb, and it got me to 98% but after doing all the setulb references it still showed the same error mesages so I knew that wasnt the issue

**Messing with other Cmake set ups to see if there is difference in CMD**

I went back to Cmake and tried generating with the files in the readme.txt said but also selecting LBFGSB and NEWUOA

this also got me to 98% with the following error mesage 

> lib\libpsuade.dll.a(d002795.o):(.text+0x0): multiple definition of `feof'

I dont know how to interpret this error mesage so i tryed undoing stuff to see if it showed me something different

I stated again without editing any files from the Psuade master file and got the exact same error at 98% but its the same error message that i dont know how to attack so ill give up on windows 10 for now.

**Conclusion**

I couldn't compile the program in W10 no matter what I tried, now I'll try to install it using windows 7 as i'm almost sure i can do it with that OS, but who knows, if that dosnt work i'll have to try making a Windows installable from Linux wich I'm even more sure it would work, if that doest work ill just give up.

Also this is only the stuff I tryed that actually made a diference in the end result, I tried more stuff but it did nothing so I didnt write it here.

**Comment by Ivan-Adriazola** [comment]
Aparently I was wrong, the Issue is not with Win10 its more with the version of GCC 9.2.0


**what heppened during this week**

Well, it worked on win7 as I was expecting but I did try new things on it since I wasnt able to install MinGW32 on win7, I got MinGW64 wich has a collection of old versions of GNU C Compiler (GCC), I installed the oldest one that didnt fail, 4.8.3 I think, but there was a .dll Missing, a .dll I remembered I had on Win10 so I installed MinGW on a second computer that had win10 just to copy this set of dll's to the Win7 PC and it finally worked but, since I did different stuff than I previusly had I retried on win10 and it also worked.


**Final instrucctions tha worked for me**

-Install CMake (newest version 3.19.1) 
-Add it to path in enviromental variables

-Install MinGW32 and download "basic pack" and "g++ pack"
-Add it to enviromental variables

-Install MinGW64 with GCC with an older version (in a different path than MinGW32)

IIRC I used: 
>version: 4.8.3
>arquitecture: x86_64
>Threads: win32
>Excepciont: seh
>Revision: 2

-Copy the files that MinGW64 created (bin,include,...,etc) in the files MinGW32 had previusly created, 
replace all if it asks you about it.

-Open cmake gui, select your source folder and build folder, configure, select "MinGW make" and select the compilers, 
-Configure again selecting as the Original Readme.txt said but also select "LBFGSB" and "NEWUOA" and Generate

-Iin CMD use the following comands
>cd "buildir"
>C:\MinGW\bin\mingw32-make.exe

-If you wanna run the test, use
>C:\MinGW\bin\mingw32-make.exe test
In my case it failed all the test, I'm not sure how concerned to be about it.

-If you wanna make a .exe for others to use, then use
>C:\MinGW\bin\mingw32-make.exe package

but for this to work on other computers they will have to also manually copy the .dll's that are on "C:\MinGW\bin" to either "system32" or to the "psuade installation folder" (i did the former) so you should copy themn into a folder and save it together with the .exe generated, and instruct other people how and where to copy the files,


**Conclusion**
I hope this is useful for someone in the future, but also I'm in no way an expert so if I'm doing something that is just stupid please do tell, I'm open to sugestions and advice of any kind, and actually something that worries me about this "installation method" is that it fails all tests, wich is kind of concerning.

The program installed using this method works, at least to the point where it opens and can run the help command, I haven't used it further than that, so I'll try to see how this goes and come back here to post a last comment if it certainly works as expected, until then I will not close this issue.

**Comment by sotorrio1** [comment]
@Ivan-Adriazola Glad to hear you were able to build psuade from source on Windows. We'll go through your whole process and make sure to document it in case someone runs into a similar issue in the future.
